### ISSUE TITLE
[QUESTION] Will “semantic recolor” be open source?

### ISSUE THREAD

**Issue by ustccxy** [MIT-SPARK/Hydra-ROS#5]
Hi, I think this project is fantastic. But there is a question I want to consult, whether semantic_recolor will be open source, I want to test on my own sensor.
thanks

**Comment by nathanhhughes** [comment]
Hi, thanks for the interest in our work! We are working on getting it released, but it is worth pointing out that it is not a required package for running Hydra against your own sensor data! With the newest release of Hydra we've actually streamlined our input interfaces, so it should be fairly straightforward to pick whatever 2D semantic segmentation network you would like and publish the predicted labels as an image alongside the RGB and depth images. You can take a look at [this](https://github.com/MIT-SPARK/Hydra-ROS/blob/63701588912c6319d5d4b88fd7f6fb0301f32ab0/hydra_ros/launch/datasets/uhumans2.launch#L28) launch file (specifically the topic arguments) to get an idea of how that might look!
